[
{
"comapanyCode": "transactional",
"originLocation": {
"locationCode": "BEN-SG",
"locationDesc":"beavuna singapore"
},
"TranspportLocation": {
"locationCode": "BEN-SG",
"locationDesc":"beavuna singapore"
}

}]